# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [41]:
# import NumPy into Python
import numpy as np
from pygments.lexers.wgsl import NotLineEndRE

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, (1000, 20))

# print the shape of X
print(X)

[[4713 2487 3551 ... 1659 4803 4241]
 [2885  896 3204 ... 1959 1025 1201]
 [ 641 4656  754 ... 4544 3146 1951]
 ...
 [4168 3981 3472 ... 3820 4555 3103]
 [ 587 1012 2206 ... 3157  633 4331]
 [4187 1679 4942 ... 1636 2784 4292]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [42]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)
print(ave_cols)
# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)


[2460.382 2580.953 2525.087 2512.698 2495.421 2508.541 2509.53  2511.635
 2536.414 2545.136 2524.099 2552.992 2449.234 2499.77  2465.302 2554.343
 2522.436 2465.952 2529.557 2501.54 ]


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [43]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [44]:
# Mean normalize X
X_norm = (X - ave_cols) / std_cols
print(X_norm)

[[ 1.53747873 -0.06391172  0.703816   ... -0.55983211  1.59141687
   1.1790424 ]
 [ 0.2898144  -1.14619274  0.46576058 ... -0.35170371 -1.05319438
  -0.88153324]
 [-1.24178229  1.41155498 -1.21503418 ...  1.44166939  0.43151194
  -0.37316754]
 ...
 [ 1.16550003  0.95238485  0.64961894 ...  0.93938617  1.41781613
   0.40768218]
 [-1.27863889 -1.0672835  -0.21890602 ...  0.4794224  -1.32759555
   1.24004629]
 [ 1.1784681  -0.61355538  1.6580958  ... -0.57578862  0.17811086
   1.21361127]]


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [45]:
# Print the average of all the values of X_norm
# You can use either the function or a method. So, there are multiple ways to solve.
print("The average of all the values of X_norm is: ")
print(np.mean(X_norm))
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print("The average of the minimum value in each column of X_norm is: ")
print(X_norm.min(axis = 0).mean())
print(np.mean(np.sort(X_norm, axis=0)[0]))

# Print the average of the maximum value in each column of X_norm
print("The average of the maximum value in each column of X_norm is: ")
print(np.mean(np.sort(X_norm, axis=0)[-1]))
print(X_norm.max(axis = 0).mean())

The average of all the values of X_norm is: 
-2.939870569207414e-17
-2.939870569207414e-17
The average of the minimum value in each column of X_norm is: 
-1.7308058431682896
-1.7308058431682896
The average of the maximum value in each column of X_norm is: 
1.7126177756453829
1.7126177756453829


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [48]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([0, 2, 1, 4, 3])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [66]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
print(X.shape[0])
row_indices = np.random.permutation(X.shape[0])
print(row_indices)

1000
[614 464 405 649 993  71 199 237 715 544 511 194 867 393 697 339 808 342
  61 994 133 848 846 612 918 135 187 332 555 444  39 481 954 705 136 300
 375 314 252 765 234 779 274 597 523 180 921 987 142 742  27 448 813 391
 316 403 775 976 925 991 850 319 480 844 764 947 888  47 246 227 861 562
 661 858 734 679 730 957 364 371 190 102 197 461 128 698 817 724 177  32
 253 595 370 974 193 985 803 605 989 628 543 773 273 459 144 454 590  19
 714 384  23 474 278 263 390 893 782 221 290 623 520  46 182 578 677 842
 967 132 892 853 807 208 345 315 508 112 757 762 218 106 880 493 851  80
  17  59 978 395 174 639 154 515 728 794 368 876 833 258 804 243 951 171
 552 616 642 805 446 117 860 878 688 226 373  48 755 610 485 559 955 407
 222 923 584 797 353 209  51 695 566 473 449 731 882  44  89 271 113 828
 509 320 349 254 159  31  75 796 392 458   1 573 883 522 121 865 239  16
 379  60 663 297 772 896 275 953 626 240   2  79 432 699 750 334 979 761
 583 166 719 327 475 387 308 645  12 307 977 8

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [75]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.

trainStartAndStopIndex = [0, int((len(row_indices) * 0.6))]
train = row_indices[np.arange(trainStartAndStopIndex[0], trainStartAndStopIndex[1])]
print( train)

crossStartAndStop = [train[1]+1, int(train[1]+1 + (len(row_indices) * 0.2))]
cross = row_indices[np.arange(crossStartAndStop[0], crossStartAndStop[1])]

test_Start_and_Stop = [cross[1]+1, int(cross[1]+1 + (len(row_indices) * 0.2) )]
test = row_indices[np.arange(test_Start_and_Stop[0], test_Start_and_Stop[1])]



# Create a Training Set
X_train = X[row_indices[train]]
print(X_train.shape)

# Create a Cross Validation Set
X_crossVal = X[row_indices[cross]]

# Create a Test Set
X_test = X[row_indices[test]]

[614 464 405 649 993  71 199 237 715 544 511 194 867 393 697 339 808 342
  61 994 133 848 846 612 918 135 187 332 555 444  39 481 954 705 136 300
 375 314 252 765 234 779 274 597 523 180 921 987 142 742  27 448 813 391
 316 403 775 976 925 991 850 319 480 844 764 947 888  47 246 227 861 562
 661 858 734 679 730 957 364 371 190 102 197 461 128 698 817 724 177  32
 253 595 370 974 193 985 803 605 989 628 543 773 273 459 144 454 590  19
 714 384  23 474 278 263 390 893 782 221 290 623 520  46 182 578 677 842
 967 132 892 853 807 208 345 315 508 112 757 762 218 106 880 493 851  80
  17  59 978 395 174 639 154 515 728 794 368 876 833 258 804 243 951 171
 552 616 642 805 446 117 860 878 688 226 373  48 755 610 485 559 955 407
 222 923 584 797 353 209  51 695 566 473 449 731 882  44  89 271 113 828
 509 320 349 254 159  31  75 796 392 458   1 573 883 522 121 865 239  16
 379  60 663 297 772 896 275 953 626 240   2  79 432 699 750 334 979 761
 583 166 719 327 475 387 308 645  12 307 977 820 30

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [77]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(600, 20)
(200, 20)
(200, 20)
