Create a 5 x 5 ndarray `X` with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array and assign the result to `Y`.

In [10]:
import numpy as np

# TODO: replace None with appropriate code
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape((5,5))
print(X)

# TODO: replace None with appropriate code
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[(X % 2 == 1)]
print(Y)
### Notebook grading
X_solution = np.arange(1,26).reshape(5,5)
Y_solution= X_solution[X_solution % 2 != 0]

if type(X) != np.ndarray or type(Y) != np.ndarray:
    print("`X` and `Y` should both be ndarrays")
elif np.array_equal(X, X_solution) and np.array_equal(Y, Y_solution):
    print("Nice work! You can view my solution below")
elif X.shape != X_solution.shape:
    print("Your answer for `X` has a shape of {} but it should be 5 x 5".format(X.shape))
elif len(Y) != len(Y_solution):
    print("Your answer for `Y` has a length of {} but it should have a length of 13".format(len(Y)))
else:
    print("Your answers have the right shape but incorrect values")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
Nice work! You can view my solution below
