Vectors:

In [5]:
import numpy as np
from lxml.xmlid import element
from pure_eval.utils import of_type

arr1 = np.array([[0.6, -15, 2, 5, 98]])
arr2 = np.array([[2, 2, -4],
                 [9, -14, 0],
                 [13, -0.5, 44],
                 [1, 9, 4],
                 [0, 0, 5]])

arr_result = np.multiply(arr1, arr2)

print(arr_result)
1 * 4

ValueError: operands could not be broadcast together with shapes (1,5) (5,3) 

In [22]:
x1 = 1
x2 = 1
w1 = 3
w2 = 4
bias = -10
w1_old = w1
w2_old = w2
b_old = bias
learning_rate = 0.1
w1_new = w1_old + learning_rate * x1
w2_new = w2_old + learning_rate * x2
b_new = b_old + learning_rate


for i in range(310):
    x1 = x1 - x1*0.1
    x2 = x2 - x2*0.1
    bias = bias - bias*0.1
    # print(f"x1 = {x1}, x2 = {2x2}, bias = {bias}")
    print(f"{i} {x1+ x2 + bias}")





0 -2.6999999999999993
1 -2.4299999999999997
2 -2.1869999999999985
3 -1.9682999999999984
4 -1.771469999999999
5 -1.5943229999999993
6 -1.4348906999999995
7 -1.2914016299999993
8 -1.1622614669999995
9 -1.0460353202999997
10 -0.9414317882699996
11 -0.8472886094429992
12 -0.762559748498699
13 -0.6863037736488291
14 -0.617673396283946
15 -0.5559060566555516
16 -0.5003154509899961
17 -0.4502839058909964
18 -0.40525551530189674
19 -0.36472996377170697
20 -0.32825696739453636
21 -0.2954312706550828
22 -0.26588814358957447
23 -0.23929932923061703
24 -0.21536939630755525
25 -0.1938324566767997
26 -0.1744492110091197
27 -0.1570042899082077
28 -0.14130386091738695
29 -0.12717347482564823
30 -0.11445612734308347
31 -0.10301051460877511
32 -0.09270946314789758
33 -0.08343851683310782
34 -0.07509466514979707
35 -0.06758519863481735
36 -0.06082667877133563
37 -0.054744010894202055
38 -0.049269609804781844
39 -0.04434264882430368
40 -0.03990838394187329
41 -0.035917545547685975
42 -0.03232579099291738


In [55]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%matplotlib inline

# Setting the random seed
# Feel free to change it to see different solutions
np.random.seed(42)

def step_function(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return step_function((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
def perceptron_step(X, y, W, b, learn_rate = 0.01):
    """
    The function should receive as inputs the data X, the labels y, the
    weights W (as an array), and the bias b, update the weights and bias
    W, b, according to the perceptron algorithm, and return W and b.
    """

    result = X @ W + b
    # print(type(result))
    # print(f"Result: {result}")
    # results = np.array([])
    # for index, element in enumerate(result):
    #     print(step_function(element))
    #     # results[index] = step_function(element)
    #
    # wrong_elements = results - y
    # print (f"Wrong elements: {wrong_elements}")
    # result = result.apply(step_function)
    # result = np.vectorize(step_function)(result)

    print(f"Result: {result}")

    # prediction = prediction(X,W,b)
    W = W  * -learn_rate;
    b = b * -learn_rate;

    print(f"Weights: {W}")
    print(f"Bias: {b}")
    # Fill in code
    return W, b

# Testing your algorithm code

X_test = np.array([[1,1],[1,-1],[-1,1],[-1,-1]])
y_test = np.array([1,1,0,0])
W_test = np.array([[0.5], [0.5]])
b_test = 0.5

output_W, output_b = perceptron_step(
    X_test,
    y_test,
    W_test,
    b_test,
    0.01
)
solution_W = np.array([[ 0.51],[ 0.49]])
solution_b = 0.49
if np.array_equal(output_W, solution_W) and output_b == solution_b:
    print("Nice work coding the perceptron algorithm!")
else:
    print("Try again. For perceptron_step(\n{}, \n{}, \n{}, \n{}, \
\n{}\n)\nthe expected result was \nW=\n{}\nand b={}, but your output \
was \nW=\n{}\nand b={}".format(
        X_test,
        y_test,
        W_test,
        b_test,
        0.01,
        solution_W,
        solution_b,
        output_W,
        output_b
    ))

Result: [[ 1.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
Weights: [[-0.005]
 [-0.005]]
Bias: -0.005
Try again. For perceptron_step(
[[ 1  1]
 [ 1 -1]
 [-1  1]
 [-1 -1]], 
[1 1 0 0], 
[[0.5]
 [0.5]], 
0.5, 
0.01
)
the expected result was 
W=
[[0.51]
 [0.49]]
and b=0.49, but your output was 
W=
[[-0.005]
 [-0.005]]
and b=-0.005


In [1]:
import numpy as np

# Sigmoid function implementation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Testing with a single value
x = 6
print("Sigmoid of 2:", sigmoid(x))

Sigmoid of 2: 0.9975273768433653


In [9]:
import math

print("e^1 =", math.exp(1))       # e to the power of 1
print("e^1 =", math.exp(2))
print("e^2 =", math.exp(5))       # e to the power of 2
print("e^0 =", math.exp(0))       # e to the power of 0
print("e^-1 =", math.exp(-1))     # e to the power of -1
print("2^1 =", 2**1)             # 2 to the power of 1
print("2^2 =", 2**2)             # 2 to the power of 2
print("2^0 =", 2**0)             # 2 to the power of 0
print("2^-1 =", 2**-1)             # 2 to the power of -1

e^1 = 2.718281828459045
e^1 = 7.38905609893065
e^2 = 148.4131591025766
e^0 = 1.0
e^-1 = 0.36787944117144233
2^1 = 2
2^2 = 4
2^0 = 1
2^-1 = 0.5
